### ISSUE TITLE
`let _` may not do what one expects

### ISSUE THREAD

**Issue by qrnch-jan** [dns2utf8/drop_guard#5]
I have a function that makes a sequence of permanent system changes.

I want all an "all or nothing" behavior for these changes; i.e. if all of them succeed, then keep the changes -- otherwise roll the changes back.

I use `drop_guard` for this purpose -- where each stage comes with its own `drop_guard::DropGuard` (to roll back the changes the function made).  In order to signal whether the guards should roll back or not I use a `RefCell<bool>` that is shared among all the `DropGuards`.  At the very bottom of the function I set the `bool` to `true`.  The guards roll back the changes if the `bool` is `false`.

While very obvious and straight-forward, this took me _way_ longer to get working than it should have, because I tried to bind the guards to `_`.  It turns out that in Rust if you use `let _ = ...` it actually doesn't even bind -- the value is dropped immediately.  This is surprising to the level that a [`must_bind`](https://internals.rust-lang.org/t/pre-rfc-must-bind/12658) attribute has been suggested.

I have two suggestions:
1) Unless the point is to explicitly demonstrate guards being dropped immediately, I would suggest that all examples using `let _ = ...` be changed to use `let _foo = ...`, and a note about this language quirk should be added to the documentation.
2) IMHO the point of `drop_guard` is somewhat diminished if the guard is dropped immediately -- so it feels like the guard is a prime example use-case for `#[must_bind]`. It should probably be noted as a todo-issue (either in code or as an project Issue).

**Comment by dns2utf8** [comment]
Hey @qrnch-jan 

Thank you for your report!

**Comment by dns2utf8** [comment]
I was able to reproduce your issue with a new test and I agree that it is a problem.
